### ISSUE TITLE
Not building with GCC 14

### ISSUE THREAD

**Issue by hv15** [xmrig/xmrig-cuda#208]
Hi,

I tried building with the latest Archlinux CUDA 12.9 + GCC14 and got the following error:

```
[ 12%] Building NVCC (Device) object CMakeFiles/xmrig-cu.dir/src/KawPow/raven/xmrig-cu_generated_KawPow.cu.o
/usr/lib/gcc/x86_64-pc-linux-gnu/14.3.1/include/c++/type_traits(1610): error: "__is_nothrow_new_constructible" is not a function or static data member
      constexpr bool __is_nothrow_new_constructible
                     ^

/usr/lib/gcc/x86_64-pc-linux-gnu/14.3.1/include/c++/type_traits(1610): error: "constexpr" is not valid here
      constexpr bool __is_nothrow_new_constructible
```

I found a similar message with another project relating to the stdcxx version, and so changes the `-std=` flag to `cxx-14` (from `cxx-11` in `cmake/flags.cmake`) which resolved the above error but still produces the following:

```
[ 12%] Building NVCC (Device) object CMakeFiles/xmrig-cu.dir/src/KawPow/raven/xmrig-cu_generated_KawPow.cu.o
/usr/lib/gcc/x86_64-pc-linux-gnu/14.3.1/include/c++/type_traits:100:52: error: redefinition of ‘constexpr const _Tp std::integral_constant<_Tp, __v>::value’
  100 |   template<typename _Tp, _Tp __v>
      |                                                    ^
/usr/lib/gcc/x86_64-pc-linux-gnu/14.3.1/include/c++/type_traits:89:29: note: ‘constexpr const _Tp value’ previously declared here
   89 |       static constexpr _Tp value = __v;
      |                             ^~~~~
```

Unfortunately I'm unsure how to further resolve this, if there is anything further I can provide, please tell me. Thanks!

**Comment by nunorfidalgo** [comment]
Hello @hv15, 

As far as I can check cuda doesn't compile with gcc14, I can build using gcc-13 in Fedora 41 with cuda 12.9, could also be applied to others systems and versions

The main point is to pass the env vars with the gcc version need to build: `CC=gcc-13 CXX=g++-13 cmake ..`

- Install GCC 13 on Fedora 41
```
sudo dnf update
sudo dnf install gcc-13 gcc13-c++
```

- Install nvidia driver
1. [rpmfusion driver](https://rpmfusion.org/Howto/NVIDIA#Current_GeForce.2FQuadro.2FTesla)
``` sudo dnf update -y 
sudo dnf install akmod-nvidia
sudo dnf install xorg-x11-drv-nvidia-cuda
sudo dnf install xorg-x11-drv-nvidia-cuda-libs
reboot ( if needed )
```

- Install cuda from nvidia repo
```
wget https://developer.download.nvidia.com/compute/cuda/repos/fedora41/x86_64/cuda-fedora41.repo
sudo cp cuda-fedora41.repo /etc/yum.repos.d/
sudo dnf update -y 
check cuda version
sudo dnf search cuda
```
- Install cuda version 
`sudo dnf install cuda-12-9`
or
`sudo dnf install cuda-12-8`

- Build xmrig-cuda with CC and CXX env vars 
```
git clone https://github.com/xmrig/xmrig-cuda.git
mkdir xmrig-cuda/build && cd xmrig-cuda/build
CC=gcc-13 CXX=g++-13 cmake .. -DCUDA_LIB=/usr/local/cuda/lib64/stubs/libcuda.so -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
make -j$(nproc)
```
